# image: $CI_REGISTRY/thunderbluff/ansible-linter:latest
image: registry.gitlab.com/pipeline-components/ansible-lint:latest

stages:
  - ansible-lint

ansible-lint:
  stage: ansible-lint
  tags:
    - docker
  script:
    - ansible-lint --show-relpath .
