---
- name: Add KeepassXC repo using key from URL
  ansible.builtin.deb822_repository:
    name: keepassxc-ppa
    types: [deb, deb-src]
    uris: https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu
    suites: ["{{ ansible_distribution_release|lower }}"]
    components: [main]
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD89C66D0E31FEA2874EBD20561922AB60068FCD6"
    state: present
    enabled: true

- name: Install KeePass XC
  ansible.builtin.apt:
    name: keepassxc
    update_cache: true
    state: present
